array:
  baseline: 20.0
  bl_max: 100.0
  bl_min: 10.0
  diameter: 2.0
  quantum_eff: 0.6
  ratio: 6.0
  spec_res: 100.0
  t_efficiency: 0.8
  t_slew: 36000.0
  throughput: 0.15
  wl_max: 18.5
  wl_min: 4.0
models:
  fov_taper: gaussian
  habitable: MS
  localzodi: darwinsim
optimization:
  N_pf: 25
  experiments:
    Experiment_1:
      in_HZ: true
      radius_p_max: 1.5
      radius_p_min: 0.5
      sample_size: 50
      temp_s_max: 7310.0
      temp_s_min: 4370.0
    Experiment_2:
      in_HZ: true
      radius_p_max: 1.5
      radius_p_min: 0.5
      sample_size: 25
      temp_s_max: 4369.0
      temp_s_min: 3320.0
    Experiment_3:
      in_HZ: true
      radius_p_max: 1.5
      radius_p_min: 0.5
      sample_size: 20
      temp_s_max: 3319.0
      temp_s_min: 2350.0
  habitable: true
  limit:
    A: .inf
    F: .inf
    G: .inf
    K: .inf
    M: .inf
  limit_mode: experiments
  opt_limit: experiments
  opt_limit_factor: 0.95
  snr_target: 7
  snr_char: 44.1
  n_orbits: 5
  t_search: 78840000.0
other:
  fov_threshold: 0.01
  image_size: 512
  n_cpu: 4
  n_plugins: 5
  output_filename: none
  output_path: none
  wl_optimal: 15
